# Generated by Django 4.2.2 on 2023-06-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
