# Generated by Django 4.2.2 on 2023-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
